<?php

namespace ResourceTs;

use ResourceTs\DTO\ResourceDefinition;

class TypescriptGenerator
{
    /**
     * Generate TypeScript type definitions from resource definitions.
     *
     * @param  ResourceDefinition[]  $definitions
     */
    public function generate(array $definitions): string
    {
        $output = $this->generateHeader();

        foreach ($definitions as $definition) {
            $output .= $this->generateType($definition);
            $output .= "\n";
        }

        return rtrim($output) . "\n";
    }

    /**
     * Generate the file header comment.
     */
    protected function generateHeader(): string
    {
        return <<<'TS'
        // This file is auto-generated by laravel-resource-ts.
        // Do not edit manually.


        TS;
    }

    /**
     * Generate a single TypeScript type definition.
     */
    protected function generateType(ResourceDefinition $definition): string
    {
        if (empty($definition->fields)) {
            return "export type {$definition->typeName} = Record<string, unknown>;\n";
        }

        $lines = ["export type {$definition->typeName} = {"];

        foreach ($definition->fields as $field) {
            $lines[] = "  {$field->toDeclaration()};";
        }

        $lines[] = '};';

        return implode("\n", $lines) . "\n";
    }
}
