<?php

use ResourceTs\DTO\FieldDefinition;
use ResourceTs\DTO\ResourceDefinition;
use ResourceTs\TypescriptGenerator;

beforeEach(function () {
    $this->generator = new TypescriptGenerator;
});

it('generates a simple type definition', function () {
    $definition = new ResourceDefinition(
        className: 'App\\Http\\Resources\\UserResource',
        typeName: 'User',
        fields: [
            new FieldDefinition('id', 'number'),
            new FieldDefinition('name', 'string'),
            new FieldDefinition('email', 'string'),
        ],
    );

    $output = $this->generator->generate([$definition]);

    expect($output)->toContain('export type User = {');
    expect($output)->toContain('  id: number;');
    expect($output)->toContain('  name: string;');
    expect($output)->toContain('  email: string;');
    expect($output)->toContain('};');
});

it('generates optional fields with question mark', function () {
    $definition = new ResourceDefinition(
        className: 'App\\Http\\Resources\\PostResource',
        typeName: 'Post',
        fields: [
            new FieldDefinition('id', 'number'),
            new FieldDefinition('secret', 'string', optional: true),
        ],
    );

    $output = $this->generator->generate([$definition]);

    expect($output)->toContain('  id: number;');
    expect($output)->toContain('  secret?: string;');
});

it('generates nullable fields with union type', function () {
    $definition = new ResourceDefinition(
        className: 'App\\Http\\Resources\\ProfileResource',
        typeName: 'Profile',
        fields: [
            new FieldDefinition('avatar', 'string', nullable: true),
        ],
    );

    $output = $this->generator->generate([$definition]);

    expect($output)->toContain('  avatar: string | null;');
});

it('generates empty types as Record<string, unknown>', function () {
    $definition = new ResourceDefinition(
        className: 'App\\Http\\Resources\\EmptyResource',
        typeName: 'Empty',
        fields: [],
    );

    $output = $this->generator->generate([$definition]);

    expect($output)->toContain('export type Empty = Record<string, unknown>;');
});

it('generates multiple types', function () {
    $definitions = [
        new ResourceDefinition(
            className: 'App\\Http\\Resources\\UserResource',
            typeName: 'User',
            fields: [new FieldDefinition('id', 'number')],
        ),
        new ResourceDefinition(
            className: 'App\\Http\\Resources\\PostResource',
            typeName: 'Post',
            fields: [new FieldDefinition('title', 'string')],
        ),
    ];

    $output = $this->generator->generate($definitions);

    expect($output)->toContain('export type User = {');
    expect($output)->toContain('export type Post = {');
});

it('includes auto-generated header comment', function () {
    $output = $this->generator->generate([]);

    expect($output)->toContain('auto-generated by laravel-resource-ts');
    expect($output)->toContain('Do not edit manually');
});
